import React from 'react';
import {
    Settings,
    Sparkles,
    Layers,
    Briefcase,
    Activity,
    Link,
    Tag,
    FileText,
    Palette,
    User,
    Users,
    Building,
    ShoppingCart,
    Calendar,
    Clock,
    Star,
    Heart,
    Award,
    Target,
    Zap,
    Shield,
    Lock,
    Unlock,
    Eye,
    Bell,
    Mail,
    Phone,
    MessageSquare,
    Camera,
    Image,
    Video,
    Music,
    Book,
    BookOpen,
    GraduationCap,
    School,
    Hospital,
    Stethoscope,
    HeartPulse,
    Car,
    Plane,
    MapPin,
    Navigation,
    Globe,
    Map,
    Home,
    Building2,
    Store,
    Coffee,
    Utensils,
    ShoppingBag,
    CreditCard,
    Wallet,
    DollarSign,
    TrendingUp,
    TrendingDown,
    BarChart,
    PieChart,
    Database,
    Server,
    Cloud,
    Folder,
    Download,
    Upload,
    Share,
    Copy,
    Save,
    Archive,
    Send,
    CheckCircle,
    XCircle,
    AlertCircle,
    Info,
    HelpCircle,
    Search,
    Filter,
    Grid as GridIcon,
    List as ListIcon,
    Menu as MenuIcon,
    RefreshCw,
    Power,
    Play,
    Pause,
    Volume2,
    Mic,
    Monitor,
    Smartphone,
    Tablet,
    Laptop,
    Wifi,
    Battery,
    Sun,
    Moon,
    Trophy,
    Medal,
    Crown,
    Gift,
    Package,
    Box as BoxIcon,
    Truck,
    Receipt,
    FileCheck,
    FileX,
    FolderOpen,
    HardDrive,
    Cpu,
    Headphones,
    Radio,
    Tv,
    Printer
} from 'lucide-react';

// Icon mapping for dynamic icon rendering
export const iconMap = {
    'Settings': Settings,
    'Sparkles': Sparkles,
    'Layers': Layers,
    'Briefcase': Briefcase,
    'Activity': Activity,
    'Link': Link,
    'Tag': Tag,
    'FileText': FileText,
    'Palette': Palette,
    'User': User,
    'Users': Users,
    'Building': Building,
    'ShoppingCart': ShoppingCart,
    'Calendar': Calendar,
    'Clock': Clock,
    'Star': Star,
    'Heart': Heart,
    'Award': Award,
    'Target': Target,
    'Zap': Zap,
    'Shield': Shield,
    'Lock': Lock,
    'Unlock': Unlock,
    'Eye': Eye,
    'Bell': Bell,
    'Mail': Mail,
    'Phone': Phone,
    'MessageSquare': MessageSquare,
    'Camera': Camera,
    'Image': Image,
    'Video': Video,
    'Music': Music,
    'Book': Book,
    'BookOpen': BookOpen,
    'GraduationCap': GraduationCap,
    'School': School,
    'Hospital': Hospital,
    'Stethoscope': Stethoscope,
    'HeartPulse': HeartPulse,
    'Car': Car,
    'Plane': Plane,
    'MapPin': MapPin,
    'Navigation': Navigation,
    'Globe': Globe,
    'Map': Map,
    'Home': Home,
    'Building2': Building2,
    'Store': Store,
    'Coffee': Coffee,
    'Utensils': Utensils,
    'ShoppingBag': ShoppingBag,
    'CreditCard': CreditCard,
    'Wallet': Wallet,
    'DollarSign': DollarSign,
    'TrendingUp': TrendingUp,
    'TrendingDown': TrendingDown,
    'BarChart': BarChart,
    'PieChart': PieChart,
    'Database': Database,
    'Server': Server,
    'Cloud': Cloud,
    'Folder': Folder,
    'Download': Download,
    'Upload': Upload,
    'Share': Share,
    'Copy': Copy,
    'Save': Save,
    'Archive': Archive,
    'Send': Send,
    'CheckCircle': CheckCircle,
    'XCircle': XCircle,
    'AlertCircle': AlertCircle,
    'Info': Info,
    'HelpCircle': HelpCircle,
    'Search': Search,
    'Filter': Filter,
    'Grid': GridIcon,
    'List': ListIcon,
    'Menu': MenuIcon,
    'RefreshCw': RefreshCw,
    'Power': Power,
    'Play': Play,
    'Pause': Pause,
    'Volume2': Volume2,
    'Mic': Mic,
    'Monitor': Monitor,
    'Smartphone': Smartphone,
    'Tablet': Tablet,
    'Laptop': Laptop,
    'Wifi': Wifi,
    'Battery': Battery,
    'Sun': Sun,
    'Moon': Moon,
    'Trophy': Trophy,
    'Medal': Medal,
    'Crown': Crown,
    'Gift': Gift,
    'Package': Package,
    'Box': BoxIcon,
    'Truck': Truck,
    'Receipt': Receipt,
    'FileCheck': FileCheck,
    'FileX': FileX,
    'FolderOpen': FolderOpen,
    'HardDrive': HardDrive,
    'Cpu': Cpu,
    'Headphones': Headphones,
    'Radio': Radio,
    'Tv': Tv,
    'Printer': Printer
};

// Available icons for selection
export const availableIcons = [
    { name: 'Settings', component: Settings },
    { name: 'Sparkles', component: Sparkles },
    { name: 'Layers', component: Layers },
    { name: 'Briefcase', component: Briefcase },
    { name: 'Activity', component: Activity },
    { name: 'Link', component: Link },
    { name: 'Tag', component: Tag },
    { name: 'FileText', component: FileText },
    { name: 'Palette', component: Palette },
    { name: 'User', component: User },
    { name: 'Users', component: Users },
    { name: 'Building', component: Building },
    { name: 'ShoppingCart', component: ShoppingCart },
    { name: 'Calendar', component: Calendar },
    { name: 'Clock', component: Clock },
    { name: 'Star', component: Star },
    { name: 'Heart', component: Heart },
    { name: 'Award', component: Award },
    { name: 'Target', component: Target },
    { name: 'Zap', component: Zap },
    { name: 'Shield', component: Shield },
    { name: 'Lock', component: Lock },
    { name: 'Unlock', component: Unlock },
    { name: 'Eye', component: Eye },
    { name: 'Bell', component: Bell },
    { name: 'Mail', component: Mail },
    { name: 'Phone', component: Phone },
    { name: 'MessageSquare', component: MessageSquare },
    { name: 'Camera', component: Camera },
    { name: 'Image', component: Image },
    { name: 'Video', component: Video },
    { name: 'Music', component: Music },
    { name: 'Book', component: Book },
    { name: 'BookOpen', component: BookOpen },
    { name: 'GraduationCap', component: GraduationCap },
    { name: 'School', component: School },
    { name: 'Hospital', component: Hospital },
    { name: 'Stethoscope', component: Stethoscope },
    { name: 'HeartPulse', component: HeartPulse },
    { name: 'Car', component: Car },
    { name: 'Plane', component: Plane },
    { name: 'MapPin', component: MapPin },
    { name: 'Navigation', component: Navigation },
    { name: 'Globe', component: Globe },
    { name: 'Map', component: Map },
    { name: 'Home', component: Home },
    { name: 'Building2', component: Building2 },
    { name: 'Store', component: Store },
    { name: 'Coffee', component: Coffee },
    { name: 'Utensils', component: Utensils },
    { name: 'ShoppingBag', component: ShoppingBag },
    { name: 'CreditCard', component: CreditCard },
    { name: 'Wallet', component: Wallet },
    { name: 'DollarSign', component: DollarSign },
    { name: 'TrendingUp', component: TrendingUp },
    { name: 'TrendingDown', component: TrendingDown },
    { name: 'BarChart', component: BarChart },
    { name: 'PieChart', component: PieChart },
    { name: 'Database', component: Database },
    { name: 'Server', component: Server },
    { name: 'Cloud', component: Cloud },
    { name: 'Folder', component: Folder },
    { name: 'Download', component: Download },
    { name: 'Upload', component: Upload },
    { name: 'Share', component: Share },
    { name: 'Copy', component: Copy },
    { name: 'Save', component: Save },
    { name: 'Archive', component: Archive },
    { name: 'Send', component: Send },
    { name: 'CheckCircle', component: CheckCircle },
    { name: 'XCircle', component: XCircle },
    { name: 'AlertCircle', component: AlertCircle },
    { name: 'Info', component: Info },
    { name: 'HelpCircle', component: HelpCircle },
    { name: 'Search', component: Search },
    { name: 'Filter', component: Filter },
    { name: 'Grid', component: GridIcon },
    { name: 'List', component: ListIcon },
    { name: 'Menu', component: MenuIcon },
    { name: 'RefreshCw', component: RefreshCw },
    { name: 'Power', component: Power },
    { name: 'Play', component: Play },
    { name: 'Pause', component: Pause },
    { name: 'Volume2', component: Volume2 },
    { name: 'Mic', component: Mic },
    { name: 'Monitor', component: Monitor },
    { name: 'Smartphone', component: Smartphone },
    { name: 'Tablet', component: Tablet },
    { name: 'Laptop', component: Laptop },
    { name: 'Wifi', component: Wifi },
    { name: 'Battery', component: Battery },
    { name: 'Sun', component: Sun },
    { name: 'Moon', component: Moon },
    { name: 'Trophy', component: Trophy },
    { name: 'Medal', component: Medal },
    { name: 'Crown', component: Crown },
    { name: 'Gift', component: Gift },
    { name: 'Package', component: Package },
    { name: 'Box', component: BoxIcon },
    { name: 'Truck', component: Truck },
    { name: 'Receipt', component: Receipt },
    { name: 'FileCheck', component: FileCheck },
    { name: 'FileX', component: FileX },
    { name: 'FolderOpen', component: FolderOpen },
    { name: 'HardDrive', component: HardDrive },
    { name: 'Cpu', component: Cpu },
    { name: 'Headphones', component: Headphones },
    { name: 'Radio', component: Radio },
    { name: 'Tv', component: Tv },
    { name: 'Printer', component: Printer }
];

/**
 * Get icon component by name
 * @param {string} iconName - Name of the icon
 * @returns {React.Component} Icon component
 */
export const getIconComponent = (iconName) => {
    const IconComponent = iconMap[iconName] || Settings;
    return <IconComponent size={18} />;
};
