package com.terrarosa.terra_crm.modules.auth.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.UUID;

/**
 * Response DTO returned when a tenant admin creates a new user.
 *
 * <p>Contains the generated temporary password which is shown to the admin
 * exactly once on the UI. The password must never be logged or stored in plain text.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TenantUserCreateResponse {

    private UUID id;
    private String email;
    private String firstName;
    private String lastName;
    private UUID tenantId;

    /**
     * The ID of the bundle assigned to the user, if any.
     */
    private UUID bundleId;

    /**
     * The name of the bundle assigned to the user, if any.
     */
    private String bundleName;

    /**
     * Temporary password generated by the system.
     * UI must show this once and never store it.
     */
    private String generatedPassword;
}

