package com.terrarosa.terra_crm.core.security.util;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Utility class for generating secure random passwords.
 *
 * <p>Passwords generated by this class:
 * <ul>
 *   <li>Use {@link SecureRandom} for cryptographic randomness</li>
 *   <li>Always contain at least one upper case letter, one lower case letter,
 *       one digit and one special character</li>
 *   <li>Are safe to store after encoding with BCrypt</li>
 * </ul>
 */
public final class RandomPasswordGenerator {

    private static final String UPPER = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    private static final String LOWER = "abcdefghijklmnopqrstuvwxyz";
    private static final String DIGITS = "0123456789";
    private static final String SPECIAL = "!@#$%^&*()-_=+[]{}";

    private static final String ALL = UPPER + LOWER + DIGITS + SPECIAL;

    private static final SecureRandom RANDOM = new SecureRandom();

    private RandomPasswordGenerator() {
        // Utility class
    }

    /**
     * Generate a secure random password with the given length.
     *
     * @param length desired password length (must be >= 8)
     * @return secure random password as plain text
     */
    public static String generateSecurePassword(int length) {
        if (length < 8) {
            throw new IllegalArgumentException("Password length must be at least 8 characters");
        }

        List<Character> passwordChars = new ArrayList<>();

        // Ensure password contains at least one character from each required group
        passwordChars.add(randomChar(UPPER));
        passwordChars.add(randomChar(LOWER));
        passwordChars.add(randomChar(DIGITS));
        passwordChars.add(randomChar(SPECIAL));

        // Fill the remaining positions with random characters from all groups
        for (int i = passwordChars.size(); i < length; i++) {
            passwordChars.add(randomChar(ALL));
        }

        // Shuffle to avoid predictable order (e.g., always starting with upper/lower/digit/special)
        Collections.shuffle(passwordChars, RANDOM);

        StringBuilder password = new StringBuilder(length);
        for (char c : passwordChars) {
            password.append(c);
        }

        return password.toString();
    }

    private static char randomChar(String chars) {
        int index = RANDOM.nextInt(chars.length());
        return chars.charAt(index);
    }
}

